version: "3"
volumes:
  node_modules:

services:
  app:
    image: vaem/encoder
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    tmpfs:
      - /app/tmp
    env_file: .env
    environment:
      - NODE_ENV=development
    command: yarn dev
